basePath: '{{.BasePath}}'
definitions:
  search.body:
    properties:
      search:
        example: madgyvers
        type: string
    type: object
host: '{{.Host}}'
info:
  contact:
    email: hi@arranzropablo.com
    name: Pablo Arranz Ropero
    url: http://arranzropablo.com
  description: This is a simple API which gets a thing to search and returns the URL
    for the wiki search.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: LMWTFY API doc
  version: "1.0"
paths:
  /search:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Creates an user
      parameters:
      - description: The string you want to search by
        in: body
        name: main
        required: true
        schema:
          $ref: '#/definitions/search.body'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Everything went OK
          schema:
            type: string
      summary: Create user
swagger: "2.0"
