package main

import (
	"github.com/arranzropablo/lmwtfy/cmd/api"
	_ "github.com/arranzropablo/lmwtfy/cmd/docs" // doc folder generated by swag init
	"github.com/arranzropablo/lmwtfy/cmd/env"
	"github.com/swaggo/http-swagger"
	"log"
	"net/http"
	"os"
)

func init() {
	env.Token = os.Getenv("LMWTFY_TOKEN")
	if env.Token == "" {
		log.Fatalln("LMWTFY_TOKEN is not set.")
	}
}

// @title LMWTFY API doc
// @version 1.0
// @description This is a simple API which gets a thing to search and returns the URL for the wiki search.
// @termsOfService http://swagger.io/terms/

// @contact.name Pablo Arranz Ropero
// @contact.url http://arranzropablo.com
// @contact.email hi@arranzropablo.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
func main() {

	http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		http.Redirect(res, req, "/swagger/index.html", http.StatusTemporaryRedirect)
	})
	http.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	http.HandleFunc("/search", search.Search)

	log.Printf("Listening on http://127.0.0.1%s", env.PORT)
	http.ListenAndServe(env.PORT, nil)
}
