package main

import (
	"github.com/arranzropablo/the-list/cmd/api"
	_ "github.com/arranzropablo/the-list/cmd/docs" // doc folder generated by swag init
	"github.com/swaggo/http-swagger"
	"log"
	"net/http"
)

const PORT = ":8888"

// @title The List API
// @version 1.0
// @description This is a sample server to store a list of films.
// @termsOfService http://swagger.io/terms/

// @contact.name Pablo Arranz Ropero
// @contact.url http://arranzropablo.com
// @contact.email hi@arranzropablo.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v1
func main() {

	http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
		http.Redirect(res, req, "/swagger/index.html", http.StatusTemporaryRedirect)
	})
	http.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	//H2 in-memory database w encrypted passwords
	http.HandleFunc("/user/new", user.CreateUser)
	http.HandleFunc("/user/edit", user.EditUser)
	//To handle dynamic endpoints (without a custom library) we can strip prefix until the dynamic part
	http.Handle("/user/", http.StripPrefix("/user/", http.HandlerFunc(user.GetUser)))

	log.Printf("Listening on http://127.0.0.1%s", PORT)
	http.ListenAndServe(PORT, nil)
}
